export const CART_TOGGLER = "CART_TOGGLER";
export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
export const REMOVE_ITEMS_FROM_CART = "REMOVE_ITEMS_FROM_CART";
export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART";
