export const POPULATE_SHOP_WITH_INVENTORY = "POPULATE_SHOP_WITH_INVENTORY";
export const FETCH_INVENTORY_START = "FETCH_INVENTORY_START";
export const FETCH_INVENTORY_SUCCESS = "FETCH_INVENTORY_SUCCESS";
export const FETCH_INVENTORY_FAIL = "FETCH_INVENTORY_FAIL";
