//GOOGLE LOGIN
export const GOOGLE_LOGIN_START = "GOOGLE_LOGIN_START";
//EMAIL LOGIN
export const EMAIL_LOGIN_START = "EMAIL_LOGIN_START";

//LOGIN
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const CHECK_USER_SESSION = "CHECK_USER_SESSION";

//LOGOUT
export const LOG_OUT_START = "LOG_OUT_START";
export const LOG_OUT_SUCCESS = "LOG_OUT_SUCCESS";
export const LOG_OUT_FAIL = "LOG_OUT_FAIL";

//REGISTER
export const REGISTER_USER_START = "REGISTER_USER_START";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";
